[Settings]
  ID = "auroratide"

[build]
  publish = "public"
  command = "npm run ci"

[[redirects]]
  from = "/api/*"
  to = "/index.html"
  status = 404
  force = false

[[redirects]]
  from = "/legal"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/whodoku"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/a-hierarchy-of-dystopias"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/as3-to-haxe-conversion"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/bloody-mess"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/candemonium"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/castle-crew-conundrum"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/chase-hamilton"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/code-highlight"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/connecting-dots-and-unassuming-assumptions"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/cosmic-upheaval"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/crazy-cab"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/dampfire"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/folderized-react-components"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/genetic-pong"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/inews-network"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/minesweeper"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/nbehave"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/nicely-testing-react-components"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/nonupo"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/omnixis"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/pt-database-app"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/shannons-maxim-and-steganography"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/solving-the-traveling-salesman"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/standard-template"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/steganography"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/tagd-igda"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/the-blue-and-gold-dress"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/thesaurus-initiative"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/three-types-of-effective-feedback"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/ti-basic-developer"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/time-to-learn-haxe"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/two-ways-to-test-react-components"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/veritasium-this-will-revolutionize-education"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/vsts-monitor"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/when-to-use-type-inference-in-haxe"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = false
