[Settings]
  ID = "auroratide"

[build]
  publish = "public"
  command = "npm run ci"

[[redirects]]
  from = "/api/*"
  to = "/index.html"
  status = 404
  force = false

[[redirects]]
  from = "/legal"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/whodoku"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/styleguide"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/art"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/a-hierarchy-of-dystopias"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/as3-to-haxe-conversion"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/connecting-dots-and-unassuming-assumptions"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/enhancing-creativity-by-deferring-judgement"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/folderized-react-components"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/meet-kafka"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/nicely-testing-react-components"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/shannons-maxim-and-steganography"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/solving-the-traveling-salesman"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/steganography"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/the-blue-and-gold-dress"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/three-types-of-effective-feedback"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/time-to-learn-haxe"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/two-ways-to-test-react-components"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/veritasium-this-will-revolutionize-education"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/posts/when-to-use-type-inference-in-haxe"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/bloody-mess"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/candemonium"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/castle-crew-conundrum"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/chase-hamilton"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/code-highlight"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/cosmic-upheaval"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/crazy-cab"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/dampfire"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/genetic-pong"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/inews-network"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/minesweeper"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/nbehave"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/nonupo"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/omnixis"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/pt-database-app"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/standard-template"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/tagd-igda"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/thesaurus-initiative"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/ti-basic-developer"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/portfolio/vsts-monitor"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/art/aurora-sci-fi"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/art/callie"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/art/fable"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/art/marscraft"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/art/noon"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/art/sky-tides"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = false
