[Settings]
  ID = "auroratide"

[build]
  publish = "public"
  command = "npm run ci"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "https://auroratide.netlify.com/*"
  to = "https://auroratide.com/:splat"
  status = 301