export const IconName = {
    AngleDoubleDown: 'angle-double-down',
    AngleDoubleLeft: 'angle-double-left',
    AngleDoubleRight: 'angle-double-right',
    AngleDoubleUp: 'angle-double-up',
    Crosshairs: 'crosshairs',
    EllipsisH: 'ellipsis-h',
    Fire: 'fire',
    Folder: 'folder',
    HandPointer: 'hand-pointer',
    HourglassHalf: 'hourglass-half',
    Image: 'image',
    LayerGroup: 'layer-group',
    Shower: 'shower',
    Undo: 'undo',

    LinkedIn: 'linked-in',
    GithubAlt: 'github-alt',
    StackOverflow: 'stack-overflow',
}
