events {}

http {
	server {
		listen 80;

		location = /web/remark.css {
			alias /etc/nginx/css/remark.css;
  			default_type text/css;
		}

		location /web-orig/ {
			proxy_pass http://remark42:8080/web/;
		}

		location / {
			proxy_pass http://remark42:8080;
			proxy_set_header Host $host;
		}
	}
}
